"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

command_timeout = 1000

[package]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true

[gradle]
disabled = true

[aws]
disabled = true
