require("config.util")
require("config.lazy")
require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.tab")
require("config.statuscolumn")
require("config.terminal")
