_:

{
  flake.modules.homeManager.pc =
    {
      lib,
      config,
      osConfig,
      ...
    }:
    let
      cfg = config.terminal.wezterm;
    in
    {
      options.terminal.wezterm.bigMonitor = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Create a padding for big monitor";
      };

      config.home.file.".config/wezterm/wezterm.lua".text = ''
        -- Auto-generated by Nix; do not edit manually
        local BIG_MONITOR = ${if cfg.bigMonitor then "true" else "false"}
        local MONOSPACE_FONT = "${osConfig.style.fonts.monospace}"

      ''
      + builtins.readFile ./wezterm.lua;
    };

  flake.modules.nixos.pc =
    { pkgs, config, ... }:
    {
      users.users.${config.people.primaryUser}.packages = [
        pkgs.wezterm
      ];
    };

  flake.modules.darwin.pc = {
    homebrew.casks = [
      "wezterm"
    ];
  };
}
