# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_7_2;

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  environment.sessionVariables = {
    # Prefer the discrete GPU (RX 9060 XT) over the iGPU as the primary
    # render/scanout device for niri and its Wayland/EGL clients.
    WLR_DRM_DEVICES = "/dev/dri/by-path/pci-0000:03:00.0-card:/dev/dri/by-path/pci-0000:10:00.0-card";
    # boot_vga is the iGPU (10:00.0), so the numeric "1" index is ambiguous;
    # pin OpenGL PRIME offload to the dGPU's PCI bus ID explicitly.
    DRI_PRIME = "pci-0000_03_00_0";
    # Vulkan clients (incl. Proton/DXVK) consult this before DRI_PRIME.
    MESA_VK_DEVICE_SELECT = "1002:7590";
  };

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "uas"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [
    # Ryzen 9700X: AMD P-State EPP (hardware-guided frequency scaling)
    "amd_pstate=active"
    # Avoid deep PCIe ASPM states, which cause link drops/stalls on the
    # onboard RTL8125B (r8169) NIC.
    "pcie_aspm.policy=performance"
  ];

  # Hibernate via swap partition
  boot.resumeDevice = "/dev/disk/by-uuid/1c6b591b-7f35-4527-b72a-0924593a1af5";

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c28253ad-8343-4e40-8f7c-d4b193148cdb";
    fsType = "btrfs";
    options = [
      "compress=zstd:1"
      "noatime"
      "space_cache=v2"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c28253ad-8343-4e40-8f7c-d4b193148cdb";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd:1"
      "noatime"
      "space_cache=v2"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/c28253ad-8343-4e40-8f7c-d4b193148cdb";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd:1"
      "noatime"
      "space_cache=v2"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D193-3BFB";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/1c6b591b-7f35-4527-b72a-0924593a1af5"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
