# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Ryzen 9700X: AMD P-State EPP (hardware-guided frequency scaling)
  boot.kernelParams = [ "amd_pstate=active" ];

  # Hibernate via swap partition
  boot.resumeDevice = "/dev/disk/by-uuid/1c6b591b-7f35-4527-b72a-0924593a1af5";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c28253ad-8343-4e40-8f7c-d4b193148cdb";
      fsType = "btrfs";
      options = [ "compress=zstd:1" "noatime" "space_cache=v2" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c28253ad-8343-4e40-8f7c-d4b193148cdb";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd:1" "noatime" "space_cache=v2" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/c28253ad-8343-4e40-8f7c-d4b193148cdb";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd:1" "noatime" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D193-3BFB";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1c6b591b-7f35-4527-b72a-0924593a1af5"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
