_:

{
  flake.modules.homeManager."terminal.wezterm" =
    {
      lib,
      config,
      ...
    }:
    let
      cfg = config.modules.terminal.wezterm;
    in
    {
      options.modules.terminal.wezterm.bigMonitor = lib.mkOption {
        type = lib.types.bool;
        default = false;
        description = "Create a padding for big monitor";
      };

      options.modules.font.monospace = lib.mkOption {
        type = lib.types.enum [
          "maple"
          "iosevka"
          "plemoljp"
          "monaspace-neon"
        ];
        default = "maple";
        description = "Monospace programming font used in the terminal";
      };

      config.home.file.".config/wezterm/wezterm.lua".text = ''
        -- Auto-generated by Nix; do not edit manually
        local BIG_MONITOR = ${if cfg.bigMonitor then "true" else "false"}
        local MONOSPACE_FONT = "${config.modules.font.monospace}"

      ''
      + builtins.readFile ./wezterm.lua;
    };

  flake.modules.nixos."terminal.wezterm" =
    { pkgs, config, ... }:
    {
      users.users.${config.people.primaryUser}.packages = [
        pkgs.wezterm
      ];
    };

  flake.modules.darwin."terminal.wezterm" = {
    homebrew.casks = [
      "wezterm"
    ];
  };
}
