{
  mkModule,
  username,
  lib,
  pkgs,
  ...
}:

with lib;

mkModule {
  name = "terminal.wezterm";
  options = {
    bigMonitor = mkEnableOption "Create a padding for big monitor";
  };
  homeModule =
    { cfg, ... }:
    let
      weztermConfig =
        ''
          -- Auto-generated by Nix; do not edit manually
          local BIG_MONITOR = ${if cfg.bigMonitor then "true" else "false"}

        ''
        + builtins.readFile ./wezterm.lua;
    in
    {
      home.file = {
        ".config/wezterm/wezterm.lua".text = weztermConfig;
      };
    };
  nixosModule = {
    users.users.${username}.packages = [
      pkgs.wezterm
    ];
  };
  darwinModule = {
    homebrew.casks = [
      "wezterm"
    ];
  };
}
