set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
set-environment -g COLORTERM "truecolor"

set-option -s set-clipboard on

set -g extended-keys always
set -as terminal-features 'xterm*:extkeys'

# General
set -g history-limit 50000
set -g display-time 2000
set -g display-panes-time 800
set -g focus-events on
set -sg repeat-time 600
set -g status-keys vi
set -g aggressive-resize on

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# Copy mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-q send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Escape send-keys -X cancel

# Windows
set -g automatic-rename on
set -g automatic-rename-format '#{?#{==:#{pane_current_command},fish},#{b:pane_current_path},#{pane_current_command}}'
set -g renumber-windows on

bind c new-window -c "#{pane_current_path}"
bind Tab last-window
bind -r p previous-window
bind -r n next-window
bind -r < swap-window -d -t -1
bind -r > swap-window -d -t +1

# Splits
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"
bind V split-window -bh -c "#{pane_current_path}"
bind S split-window -bv -c "#{pane_current_path}"
bind N split-window -bh -l 25% -c "#{pane_current_path}"

# Pane navigation
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# Pane resizing
bind -r C-k resize-pane -U 5
bind -r C-j resize-pane -D 5
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5

# Layouts
bind -r Space next-layout
bind = select-layout tiled

# Pane management
bind o kill-pane -a

# Sessions
bind e choose-session
bind C-c new-session

# Tools
bind g display-popup -d '#{pane_current_path}' -w100% -h100% -E lazygit
