name: main

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: set vars.nix
        run: |
          DEFAULT_VARS=$(nix --extra-experimental-features 'nix-command' eval --file ./vars.nix.example)
          OVERRIDES='{
            username = "runner";
            homeDirectory = "/home/runner";
            system = "x86_64-linux";
          }'
          VARS=$(nix --extra-experimental-features 'nix-command' eval --expr "$DEFAULT_VARS // $OVERRIDES")

      - name: install dotfiles
        run: ./init.sh
